sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: 'eu-west-1'
    app: 'docker_react'
    env: 'DockerReact-env'
    bucket_name: 'elasticbeanstalk-eu-west-1-878317546226'
    bucket_path: 'docker_react'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY